// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_ZDz1fvFRJPUYxTpdMxZXhrhPD6th4c',
    appId: '1:510368523955:web:3de25b8d7a6656f6beb2c6',
    messagingSenderId: '510368523955',
    projectId: 'firefly-b98c5',
    authDomain: 'firefly-b98c5.firebaseapp.com',
    storageBucket: 'firefly-b98c5.appspot.com',
    measurementId: 'G-7XXD6T0MHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRCdeDb1XmbjYAtBag8BxJKea1U7rmjw',
    appId: '1:510368523955:android:7fa8eb610a92e600beb2c6',
    messagingSenderId: '510368523955',
    projectId: 'firefly-b98c5',
    storageBucket: 'firefly-b98c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43IeCJp2HEtbNFnMgM4Hc2UhZo1OZHhg',
    appId: '1:510368523955:ios:a1795b10cf26facebeb2c6',
    messagingSenderId: '510368523955',
    projectId: 'firefly-b98c5',
    storageBucket: 'firefly-b98c5.appspot.com',
    iosBundleId: 'com.example.fireflyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43IeCJp2HEtbNFnMgM4Hc2UhZo1OZHhg',
    appId: '1:510368523955:ios:a1795b10cf26facebeb2c6',
    messagingSenderId: '510368523955',
    projectId: 'firefly-b98c5',
    storageBucket: 'firefly-b98c5.appspot.com',
    iosBundleId: 'com.example.fireflyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_ZDz1fvFRJPUYxTpdMxZXhrhPD6th4c',
    appId: '1:510368523955:web:7270b0c284628791beb2c6',
    messagingSenderId: '510368523955',
    projectId: 'firefly-b98c5',
    authDomain: 'firefly-b98c5.firebaseapp.com',
    storageBucket: 'firefly-b98c5.appspot.com',
    measurementId: 'G-NRV9K5HK7L',
  );
}
