// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05YpKq6SQlT87jZWmQFirL_goJ2Zoh7E',
    appId: '1:719260730895:web:650927015b862c88cd057a',
    messagingSenderId: '719260730895',
    projectId: 'firefly-task',
    authDomain: 'firefly-task.firebaseapp.com',
    storageBucket: 'firefly-task.appspot.com',
    measurementId: 'G-2ZD3DYBB8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqkpJax0RDp0hZjMVSbYX0C_whZsRyaOQ',
    appId: '1:719260730895:android:6a7e0e1a04560c1ecd057a',
    messagingSenderId: '719260730895',
    projectId: 'firefly-task',
    storageBucket: 'firefly-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb2LxTkljEJjqRnYTI4wqM-QT9hFBEnLo',
    appId: '1:719260730895:ios:1b3913bc9589b38acd057a',
    messagingSenderId: '719260730895',
    projectId: 'firefly-task',
    storageBucket: 'firefly-task.appspot.com',
    iosBundleId: 'com.example.fireflyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb2LxTkljEJjqRnYTI4wqM-QT9hFBEnLo',
    appId: '1:719260730895:ios:1b3913bc9589b38acd057a',
    messagingSenderId: '719260730895',
    projectId: 'firefly-task',
    storageBucket: 'firefly-task.appspot.com',
    iosBundleId: 'com.example.fireflyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD05YpKq6SQlT87jZWmQFirL_goJ2Zoh7E',
    appId: '1:719260730895:web:6ca8e206635982d6cd057a',
    messagingSenderId: '719260730895',
    projectId: 'firefly-task',
    authDomain: 'firefly-task.firebaseapp.com',
    storageBucket: 'firefly-task.appspot.com',
    measurementId: 'G-Q7HCPDE0WM',
  );
}
